INSERT INTO [dbo].[LeaveTypes] ([LeaveType]) VALUES (N'Bereavment')
INSERT INTO [dbo].[LeaveTypes] ([LeaveType]) VALUES (N'Casual')
INSERT INTO [dbo].[LeaveTypes] ([LeaveType]) VALUES (N'Casual - Probation')
INSERT INTO [dbo].[LeaveTypes] ([LeaveType]) VALUES (N'Compensatory Leave')
INSERT INTO [dbo].[LeaveTypes] ([LeaveType]) VALUES (N'Earn Leave')
INSERT INTO [dbo].[LeaveTypes] ([LeaveType]) VALUES (N'FMLA')
INSERT INTO [dbo].[LeaveTypes] ([LeaveType]) VALUES (N'Lieu Leave')
INSERT INTO [dbo].[LeaveTypes] ([LeaveType]) VALUES (N'Maternity')
INSERT INTO [dbo].[LeaveTypes] ([LeaveType]) VALUES (N'Medical')
INSERT INTO [dbo].[LeaveTypes] ([LeaveType]) VALUES (N'Paternity')
INSERT INTO [dbo].[LeaveTypes] ([LeaveType]) VALUES (N'PTO')
INSERT INTO [dbo].[LeaveTypes] ([LeaveType]) VALUES (N'Vacation')
INSERT INTO [dbo].[LeaveTypes] ([LeaveType]) VALUES (N'Work For Home')
