INSERT INTO [dbo].[Employees] ([EmployeeID], [EmployeeName], [Department], [Designation], [Salary]) VALUES (1, N'Muhammad Ikram Khan', N'IT', N'OM', 500000)
INSERT INTO [dbo].[Employees] ([EmployeeID], [EmployeeName], [Department], [Designation], [Salary]) VALUES (2, N'Dipto Gomes', N'IT', N'OM', 400000)
INSERT INTO [dbo].[Employees] ([EmployeeID], [EmployeeName], [Department], [Designation], [Salary]) VALUES (3, N'Shubho Brata', N'IT', N'OM', 400000)
INSERT INTO [dbo].[Employees] ([EmployeeID], [EmployeeName], [Department], [Designation], [Salary]) VALUES (4, N'Abir Pahlwan', N'IT', N'OM', 400000)
INSERT INTO [dbo].[Employees] ([EmployeeID], [EmployeeName], [Department], [Designation], [Salary]) VALUES (5, N'Halimuzzaman', N'IT', N'OM', 400000)
INSERT INTO [dbo].[Employees] ([EmployeeID], [EmployeeName], [Department], [Designation], [Salary]) VALUES (6, N'Asif Noor Rafiul Karim', N'HR', N'OM', 600000)
INSERT INTO [dbo].[Employees] ([EmployeeID], [EmployeeName], [Department], [Designation], [Salary]) VALUES (7, N'Muntasir Ahmed', N'IT', N'DD', 550000)
INSERT INTO [dbo].[Employees] ([EmployeeID], [EmployeeName], [Department], [Designation], [Salary]) VALUES (8, N'Heavymetal Shourov', N'DM', N'OM', 200000)
INSERT INTO [dbo].[Employees] ([EmployeeID], [EmployeeName], [Department], [Designation], [Salary]) VALUES (9, N'Debashish Chandra', N'HR', N'OM', 400000)
INSERT INTO [dbo].[Employees] ([EmployeeID], [EmployeeName], [Department], [Designation], [Salary]) VALUES (10, N'Gopaillah', N'IT', N'Food', 15000)
